name: "\U0001F41B Bug report"
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      value: ""
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      value: ""
    validations:
      required: true

  - type: dropdown
    id: bandit-version
    attributes:
      label: Bandit version
      description: Run "bandit --version" if unsure of version number
      options:
        - 1.7.0 (Default)
        - 1.6.3
        - 1.6.2
        - 1.6.1
        - 1.6.0
        - 1.5.1
        - 1.5.0
        - 1.4.0
        - 1.3.0
        - 0.17.0-eol
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: Run "bandit --version" if unsure of version number
      options:
        - 3.9 (Default)
        - 3.8
        - 3.7
        - 3.6
        - 3.5
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      value: ""
    validations:
      required: true
